### ISSUE TITLE
OSRM data is outdated

### ISSUE THREAD

**Issue by fellipessanha** [loggi/loggibud#23]
The current compiled OSRM maps aren't working properly on the osrm/backend docker image, who spits this error message when I try to use it:

`[error] File is incompatible with this version of OSRM: /data/brazil-201110.osrm.icd prepared with OSRM 5.24.0 but this is v5.26.0 (at include/storage/tar.hpp:205)`

Also the [Geofabrik link](http://download.geofabrik.de/south-america/brazil-201110.osm.pbf), available in [docs/osrm.md](./docs/osrm.md) isn't available. I already recompiled the data here, but I think it would be best to have a canon file for everyone to use ;)

**Comment by fillipe-gsm** [comment]
Thanks for pointing that out, @fellipessanha. The problem was the discrepancies between the OSRM container version used to compile the data, and the one you used to run it. We need to make sure they are the same.

Personally, I would suggest to update the `docs` to explicitly download the 5.24.0 container version with

```
docker pull osrm/osrm-backend:v5.24.0
```

Even if we recompile the data with the latest version 5.26.0, eventually a newer one would be released and the problem would happen again, so I believe this is the safest option.

What do you think, @gabisurita?

**Comment by fillipe-gsm** [comment]
With respect to the Geofabrik link, thanks again for pointing it. We will update it :)

**Comment by gabisurita** [comment]
+1 for pinning the OSRM version in v5.24. Thanks for pointing this out.

**Comment by gabisurita** [comment]
Pinned OSRM version in https://github.com/loggi/loggibud/commit/4cfec0385b2b11bbe5683c4992c129cbe1040a0b.
